name: "Chromatic deploy do docs"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: chromatic
